### ISSUE TITLE
install fails on mac m2

### ISSUE THREAD

**Issue by coke** [krunen/term-termios#20] opened 2023-08-20 20:46 UTC
```
✗ raku --version
Welcome to Rakudo™ v2023.06-241-gcb8d2a125.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.06-4-g75fe055c2.
...
===> Building: Term::termios:ver<0.2.6>:auth<zef:krunen>
[Term::termios] Command: /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/bin/rakudo -I/var/folders/8n/rypl9_990b9578zd5435pgr40000gn/T/.zef/1692564298.8422/Distribution%3A%3ABuilder%3A%3AMakeFromJSON%3Aver%3C0.6%3E%3Aauth%3Cgithub%3Aniner%3E.tar.gz/Distribution-Builder-MakeFromJSON-master -I/var/folders/8n/rypl9_990b9578zd5435pgr40000gn/T/.zef/1692564298.8422/d254fdd0efd10a06bde98ee99b6ab1349532760a.tar.gz -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/var/folders/8n/rypl9_990b9578zd5435pgr40000gn/T/.zef/1692564298.8422/b7707185f4d678efd41f95d08a06dc13560c6f3f.tar.gz/dist|)??0!!1)
===> Building [FAIL]: Term::termios:ver<0.2.6>:auth<zef:krunen>
Aborting due to build failure: Term::termios:ver<0.2.6>:auth<zef:krunen> (use --force-build to override)
```

**Comment by coke** [comment] 2023-08-20 20:50
bisected master, first commit to fail 'zef test .' is 94048572d922885954f0b32796ef816ad5d550e4

**Comment by krunen** [comment] 2023-08-20 20:53
Can you try with zef --debug? I have no access to a mac.

**Comment by coke** [comment] 2023-08-20 20:54
from a fresh clone:
```
➜  term-termios git:(master) zef --debug test .
===> Testing: Term::termios:ver<0.2.6>:auth<zef:krunen>
[Term::termios] Testing with plugin: Zef::Service::Shell::prove
[Term::termios] Cannot locate native library '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib': dlopen(/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib, 0x000A): tried: '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file), '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file)
[Term::termios]   in method setup at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/DF11ACA1332FEF4D650A7A4E767FB70FD18E62BE (NativeCall) line 319
[Term::termios]   in method setup at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/DF11ACA1332FEF4D650A7A4E767FB70FD18E62BE (NativeCall) line 366
[Term::termios]   in sub raku-nativecall at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/438D8570588BACDEF52787B63B52F944D6B57C2F (NativeCall::Dispatcher) line 46
[Term::termios]   in method overwrite_constant at /Users/coke/sandbox/term-termios/lib/Term/termios.rakumod (Term::termios) line 157
[Term::termios]   in submethod BUILD at /Users/coke/sandbox/term-termios/lib/Term/termios.rakumod (Term::termios) line 174
[Term::termios]   in block <unit> at t/basic.t line 8
[Term::termios] # You planned 2 tests, but ran 1
[Term::termios] t/basic.t ..
[Term::termios] 1..2
[Term::termios] ok 1 - use
[Term::termios] Dubious, test returned 255 (wstat 65280, 0xff00)
[Term::termios] Failed 1/2 subtests
[Term::termios] Test Summary Report
[Term::termios] -------------------
[Term::termios] t/basic.t (Wstat: 65280 Tests: 1 Failed: 0)
[Term::termios]   Non-zero exit status: 255
[Term::termios]   Parse errors: Bad plan.  You planned 2 tests but ran 1.
[Term::termios] Files=1, Tests=1,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.30 cusr  0.01 csys =  0.33 CPU)
[Term::termios] Result: FAIL
===> Testing [FAIL]: Term::termios:ver<0.2.6>:auth<zef:krunen>
Aborting due to test failure: Term::termios:ver<0.2.6>:auth<zef:krunen> (use --force-test to override)
```

**Comment by krunen** [comment] 2023-08-20 21:00
I just released 0.2.7 with a change that may fix the issue.

**Comment by coke** [comment] 2023-08-20 21:01
```
===> Testing: Term::termios:ver<0.2.7>:auth<zef:krunen>
[Term::termios] Testing with plugin: Zef::Service::Shell::prove
[Term::termios] Cannot locate native library '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib': dlopen(/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib, 0x000A): tried: '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file), '/Users/coke/sandbox/term-termios/resources/libraries/libmyhelper.dylib' (no such file)
[Term::termios]   in method setup at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/DF11ACA1332FEF4D650A7A4E767FB70FD18E62BE (NativeCall) line 319
[Term::termios]   in method setup at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/DF11ACA1332FEF4D650A7A4E767FB70FD18E62BE (NativeCall) line 366
[Term::termios]   in sub raku-nativecall at /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/share/perl6/core/sources/438D8570588BACDEF52787B63B52F944D6B57C2F (NativeCall::Dispatcher) line 46
[Term::termios]   in method overwrite_constant at /Users/coke/sandbox/term-termios/lib/Term/termios.rakumod (Term::termios) line 157
[Term::termios]   in submethod BUILD at /Users/coke/sandbox/term-termios/lib/Term/termios.rakumod (Term::termios) line 174
[Term::termios]   in block <unit> at t/basic.t line 8
[Term::termios] # You planned 2 tests, but ran 1
[Term::termios] t/basic.t ..
[Term::termios] 1..2
[Term::termios] ok 1 - use
[Term::termios] Dubious, test returned 255 (wstat 65280, 0xff00)
[Term::termios] Failed 1/2 subtests
[Term::termios] Test Summary Report
[Term::termios] -------------------
[Term::termios] t/basic.t (Wstat: 65280 Tests: 1 Failed: 0)
[Term::termios]   Non-zero exit status: 255
[Term::termios]   Parse errors: Bad plan.  You planned 2 tests but ran 1.
[Term::termios] Files=1, Tests=1,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.32 cusr  0.01 csys =  0.35 CPU)
[Term::termios] Result: FAIL
===> Testing [FAIL]: Term::termios:ver<0.2.7>:auth<zef:krunen>
Aborting due to test failure: Term::termios:ver<0.2.7>:auth<zef:krunen> (use --force-test to override)
```

**Comment by krunen** [comment] 2023-08-20 21:04
zef / Distribution::Builder::MakeFromJSON is supposed to build the dylib file.

**Comment by krunen** [comment] 2023-08-20 21:08
```
krunen@LAPTOP-TKMV4O0L:~/src/term-termios$ zef --debug build .
===> Building: Term::termios:ver<0.2.7>:auth<zef:krunen>
[Term::termios] Building with plugin: Zef::Service::Shell::DistributionBuilder
[Term::termios] Command: /home/krunen/.rakubrew/versions/moar-2023.06/bin/rakudo -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/home/krunen/src/term-termios|)??0!!1)
[Term::termios] gcc -shared -fPIC  -O3 -DNDEBUG -Wl,-z,origin,-rpath,'$ORIGIN/../lib'  -lm -lpthread -lrt -ldl -o /home/krunen/src/term-termios/resources/libraries/libmyhelper.so myhelper.o
===> Building [OK] for Term::termios:ver<0.2.7>:auth<zef:krunen>
```

**Comment by coke** [comment] 2023-08-20 21:11
tests pass on zef test . with Distribution::Builder::MakeFromJSON.

**Comment by krunen** [comment] 2023-08-20 21:14
What output do you get from "zef --debug build ." in term-termios? Does it compile the dylib?

**Comment by coke** [comment] 2023-08-20 21:16
```
➜  term-termios git:(master) zef --debug build .
===> Building: Term::termios:ver<0.2.7>:auth<zef:krunen>
[Term::termios] Building with plugin: Zef::Service::Shell::DistributionBuilder
[Term::termios] Command: /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/bin/rakudo -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/Users/coke/sandbox/term-termios|)??0!!1)
===> Building [FAIL]: Term::termios:ver<0.2.7>:auth<zef:krunen>
Aborting due to build failure: Term::termios:ver<0.2.7>:auth<zef:krunen> (use --force-build to override)
```

**Comment by krunen** [comment] 2023-08-20 21:19
So no help there, unfortunately.
I have no clue how to fix this without access to a mac.
If you know of a different module that compiles a small c helper and works on the Mac, that uses fez, I can have a look at how it is done there.

**Comment by coke** [comment] 2023-08-20 22:35
It worked fine at the previously mentioned commit.

**Comment by krunen** [comment] 2023-08-21 16:44
Distribution::Builder::MakeFromJSON first generates a file "Makefile" based on "Makefile.in", then it runs "make", which should run the c-compiler and linker to create the dylib file. Can you check if you have the Makefile, and see if you have any *.o files or other new files after running build?

**Comment by coke** [comment] 2023-08-22 00:22
`zef build .` generates the makefile but doesn't invoke `make`; if I manually invoke `make` then `zef test .` succeeds.

**Comment by hythm7** [comment] 2023-08-22 02:07
> ```
> [Term::termios] Command: /Users/coke/.rakubrew/versions/moar-cb8d2a125/install/bin/rakudo -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/Users/coke/sandbox/term-termios|)??0!!1)
> ===> Building [FAIL]: Term::termios:ver<0.2.7>:auth<zef:krunen>
> Aborting due to build failure: Term::termios:ver<0.2.7>:auth<zef:krunen> (use --force-build to override)
> ```
This shows Building FAIL only, shouldn't the output or the error from the command process appear in the debug output to see why it actually failed?

May be running that command manually (if the directories not cleaned) will show why it's failing?

`/Users/coke/.rakubrew/versions/moar-cb8d2a125/install/bin/rakudo -MMONKEY-SEE-NO-EVAL -e exit((require ::(q|Distribution::Builder::MakeFromJSON|)).new(:meta(EVAL($*IN.slurp(:close)))).build(q|/Users/coke/sandbox/term-termios|)`

**Comment by coke** [comment] 2023-08-22 02:15
If I extract the output from the zef build, put it in a script and run it, it hangs - what is getting passed to this with the $*IN.slurp?

**Comment by hythm7** [comment] 2023-08-22 02:19
Not exactly sure but it would be the META6.json file content so MakeDlFromJSON can extract the "build" hash from it.

**Comment by hythm7** [comment] 2023-08-22 02:50
[this](https://gist.github.com/hythm7/9861cbfa7d448bb5b4d16c1d9dd6edb5) script builds Term::termios successfully for me on Linux (may be if run on mac will show the error).  first I `cd`  to termios directory then:

```sh
raku -I. /tmp/build-termios.raku
gcc -c -fPIC -std=gnu99 -Wextra -Wall -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Werror=pointer-arith -Werror=vla -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=3 -D_GNU_SOURCE -o  myhelper.o src/myhelper.c
gcc -shared -fPIC  -O3 -DNDEBUG -Wl,-rpath,"//home/hythm/.rakubrew/versions/moar-HEAD-HEAD-HEAD/install/lib"  -lm -lpthread -lrt -ldl -lzstd  -o /tmp/740B06AC0BF94E91D837D5894F9872DD53151ABA/1692671811.0771186/resources/libraries/libmyhelper.so myhelper.o
```

**Comment by coke** [comment] 2023-08-22 02:55
the makefile works for me, it just isn't run.

**Comment by krunen** [comment] 2023-08-22 05:51
The MakeFromJSON build method is very simple, could you maybe get a local copy and add some debug 'note's?

**Comment by coke** [comment] 2023-08-22 20:35
I put some debug output in, and basically:

```
run $make, :cwd($src-dir);
```
is failing with:
```
[Term::termios] Proc.new(in => IO::Pipe, out => IO::Pipe, err => IO::Pipe, exitcode => 1, signal => 0, pid => Nil, command => ("make",))
```
but if I run make in the src-dir, it works fine.

**Comment by hythm7** [comment] 2023-08-22 21:35
anything shows when using:
`my $proc = run $make, :out, :err, :cwd($src-dir); .say for $proc.out.lines; .say for $proc.err.lines;`
instead of `run $make, :cwd($src-dir);`?

**Comment by coke** [comment] 2023-08-22 21:46
No output

**Comment by krunen** [comment] 2023-08-22 21:50
How about something like this:
```
~/src/term-termios$ raku -e 'run "make"'
make: Nothing to be done for 'all'.
```

**Comment by ugexe** [comment] 2023-08-22 21:52
For whatever reason if `Distribution::JSON::MakeFromJSON` is changed to not output the stdout/stderr to e.g. terminal it works as expected. Its as if the buffers containing stdout and/or stderr affect the error code that is returned from the run command below

```
diff --git a/lib/Distribution/Builder/MakeFromJSON.pm6 b/lib/Distribution/Builder/MakeFromJSON.pm6
index d02dc6e..cf7c043 100644
--- a/lib/Distribution/Builder/MakeFromJSON.pm6
+++ b/lib/Distribution/Builder/MakeFromJSON.pm6
@@ -38,7 +38,7 @@ method build(IO() $work-dir = $*CWD) {
         run $make, $meta<make-target>, :cwd($src-dir);
     }
     else {
-        run $make, :cwd($src-dir);
+        run $make, :cwd($src-dir), :!out, :!err;
     }
 }
```
With just that change the containing function now correctly returns True for the make command. Seems like there might be a rakudo bug at the root of this.

**Comment by coke** [comment] 2023-08-22 21:54
@ugexe  - that doesn't fix my issue.

**Comment by ugexe** [comment] 2023-08-22 21:59
@coke Strange, the first time I run build after making that change it succeeds (and has the output `make: Nothing to be done for all`. But if I run build again it fails with no output.

**Comment by ugexe** [comment] 2023-08-22 22:07
OK this change (which appears to fix it for me) makes a little more sense, since invoking `Distribution::Builder::MakeFromJSON` is passed data via `$*IN`:
```
diff --git a/lib/Distribution/Builder/MakeFromJSON.pm6 b/lib/Distribution/Builder/MakeFromJSON.pm6
index d02dc6e..9b1d651 100644
--- a/lib/Distribution/Builder/MakeFromJSON.pm6
+++ b/lib/Distribution/Builder/MakeFromJSON.pm6
@@ -38,7 +38,7 @@ method build(IO() $work-dir = $*CWD) {
         run $make, $meta<make-target>, :cwd($src-dir);
     }
     else {
-        run $make, :cwd($src-dir);
+        run $make, :cwd($src-dir), :!in;
     }
 }
```

**Comment by coke** [comment] 2023-08-22 22:10
Yup, that did it!

**Comment by ugexe** [comment] 2023-08-22 22:10
You can run these commands in the e.g. `Term::termios` directory (or anythign with a makefile) to see the aforementioned behavior on macOS:
```
raku -e 'say so shell("make")'
make: Nothing to be done for `all'.
True
```
```
raku -e '$*IN.close; say so shell("make")'
False
```

**Comment by ugexe** [comment] 2023-08-22 22:19
https://github.com/rakudo/rakudo/issues/5357

**Comment by ugexe** [comment] 2023-08-23 20:04
I'll be releasing a workaround in the next version (v0.18.4) of zef

**Comment by jubilatious1** [comment] 2023-09-16 17:08
Not sure if this is helpful, but `Term::Termios` seems to have installed fine on my `M2` Mac. 

```
Last login: Sat Sep 16 03:26:23 on ttys049
admin@mbp rakudo-2023.05 % /Users/admin/rakudo/rakudo-2023.05/install/share/perl6/site/bin/zef install Term::termios --verbose
The following candidates are already installed: Term::termios
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway
```

**Comment by krunen** [comment] 2023-09-21 21:43
I'm closing this as it seems the issue is solved in zef

**Closed by krunen** 2023-09-21 21:43 UTC
